#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string


sudo apt-get update
sudo apt-get install -y nginx


echo "Hello World!" | sudo tee /var/www/html/index.html


sudo sed -i '/server_name _;/a \\
    rewrite ^/redirect_me https://www.blog.ehoneahobed.com permanent;' /etc/nginx/sites-enabled/default


echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html


sudo sed -i '/listen 80 default_server;/a \\
    error_page 404 /404.html;\n\
    location = /404.html {\n\
        root /var/www/html;\n\
        internal;\n\
    }' /etc/nginx/sites-enabled/default


sudo service nginx reload
