#!/usr/bin/env bash

# bash script that displays listening ports:
# - Shows only listening sockets
# - Shows the PID and name of the program to which each socket belongs 
# Display active Internet connections (only servers)

netstat -l -p