#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while
# on the 9th iteration, display "hi" before "best school" 

count=0

while [ $count -lt 10 ]
do
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    (( count++ ))
done