#!/usr/bin/env bash
# loops from 1 to 10 and displays :
# "bad luck" in the 4th iteration
# "good luck" in the 8th iteration
# "best school" in the other iteration 

count=0

while [ $count -lt 10 ]
do
    if [ $count -eq 3 ]
    then
        echo "bad luck"
    elif [  $count  -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( count++ ))
done