#!/usr/bin/env bash
# loops from 1 to 20 and displays :
# "bad luck from China" in the 4th iteration
# "bad luck from Japan" in the 9th iteration
# "bad luck from Italy" in the 17th iteration
count=0

while [ $count -le 20 ]
do
    echo "$count"
    case $count in
            "4") echo "bad luck from China";;
          "9") echo "bad luck from Japan";;
         "17") echo "bad luck from Italy";;
    esac
    (( count++ ))
done