#!/usr/bin/env bash
# displays the contents of the current directory in list format
# only displays the part of the name after the first dash

list=$(1s)
for i in $list; do
    echo "$i" | cut -d '-' -f2
done
